# Generated by Django 6.0.2 on 2026-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refund_reference',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
